# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecstop < Formula
  desc ""
  homepage ""
  version "0.0.1-alpha4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/t-kikuc/ecstop/releases/download/v0.0.1-alpha4/ecstop_0.0.1-alpha4_Darwin_x86_64.tar.gz"
      sha256 "b10256624a298bfd63703f9187a4a34c79fb3ea9f633979d26a5ac547a23eb3a"

      def install
        bin.install "ecstop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/t-kikuc/ecstop/releases/download/v0.0.1-alpha4/ecstop_0.0.1-alpha4_Darwin_arm64.tar.gz"
      sha256 "5f835aa81a554eba3410701d367f2ce47e5601a213c15d5ddf16f9be550e574e"

      def install
        bin.install "ecstop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/t-kikuc/ecstop/releases/download/v0.0.1-alpha4/ecstop_0.0.1-alpha4_Linux_x86_64.tar.gz"
        sha256 "2dec0f8e265acf0fd8662739f17eb27079d3795b532f75b35c93a4454f3fae13"

        def install
          bin.install "ecstop"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/t-kikuc/ecstop/releases/download/v0.0.1-alpha4/ecstop_0.0.1-alpha4_Linux_arm64.tar.gz"
        sha256 "43d4ea480dae71f7d8b57a0a30971ede3c8570e0a53043ebe42c57fc5381e444"

        def install
          bin.install "ecstop"
        end
      end
    end
  end
end
